services:
  mysql:
    container_name: 'mysqldb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=laborganized_dev'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
